# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('init_date', models.DateTimeField(blank=True, null=True)),
                ('controller', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PassTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='passevent',
            name='pass_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acs_app.PassTypes'),
        ),
    ]
