# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passevent',
            name='card',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='passevent',
            name='department',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='passevent',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='passevent',
            name='patronymic',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='passevent',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='passevent',
            name='surname',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='passtypes',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='passevent',
            name='controller',
            field=models.TextField(null=True),
        ),
    ]
