# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_app', '0004_auto_20170414_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passevent',
            name='patronymic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
