# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs_app', '0005_auto_20170414_0102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PassTypes',
            new_name='PassType',
        ),
    ]
