# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acs_app', '0006_auto_20170414_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passevent',
            name='pass_type',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='PassType',
        ),
    ]
